# Canonical owner: closed-loop-dbs-bench
"""Synthetic beta trajectory and stimulation generation for public benchmarking.

All public repos work exclusively with synthetic data produced here.  Researchers
with access to patient recordings can plug in real data via the schema in
``dbs_bench.synthetic.schema``.

Physics:
    The synthetic beta signal is generated by the same AR + stimulation model
    used in simulation (``BetaSimulator`` in ``dbs_bench.simulation.simulate``):

        y_beta(k) = a1*y_beta(k-1) + a2*y_beta(k-2) + a3*y_beta(k-3) + noise + bias
        eta(k)    = C @ x_eta(k)
        x_eta(k+1) = A_eta @ x_eta(k) + B_eta * u(k)
        y(k)      = y_beta(k) - eta(k)   (log-domain additive)

    Parameters are taken directly from ``device_params.json`` defaults.

Example:
    >>> from dbs_bench.synthetic.data_generator import (
    ...     generate_synthetic_beta,
    ...     generate_demo_patient,
    ...     generate_demo_dataset,
    ... )
    >>> beta = generate_synthetic_beta(n_steps=5000, seed=42)
    >>> patient = generate_demo_patient(n_state_y=15)
    >>> beta_traj, patient = generate_demo_dataset(duration=60.0, dt=0.02)
"""
from __future__ import annotations

import math
from typing import Optional, Tuple

import numpy as np

# ---------------------------------------------------------------------------
# AR model defaults (from device_params.json / BetaSimulator defaults)
# ---------------------------------------------------------------------------
_AR_COEFFS = (0.35, -0.08, 0.04)   # a1, a2, a3
_AR_BIAS = 0.015                     # small positive drift keeps beta in range
_AR_NOISE_STD = 0.0012               # process noise std
_STIM_GAIN = 62.11                   # CDC24 nominal gain
_STIM_TAU1 = 0.05                    # time constant 1 (s)
_STIM_TAU2 = 0.25                    # time constant 2 (s)
_DT = 0.02                           # sample period (50 Hz)
_U_MAX = 0.030                       # max stimulation amplitude
_DELTA_U_MAX = 0.0024                # max increment per step


def _build_stim_matrices(
    gain: float = _STIM_GAIN,
    tau1: float = _STIM_TAU1,
    tau2: float = _STIM_TAU2,
    dt: float = _DT,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Return discrete-time (Ad, Bd, Cd) for the 2nd-order stimulation model.

    Uses the analytical closed-form ZOH discretisation (avoids scipy dependency
    for a simple lower-triangular system).
    """
    e1 = math.exp(-dt / tau1)
    e2 = math.exp(-dt / tau2)
    inv_diff = 1.0 / (1.0 / tau2 - 1.0 / tau1)
    ad10 = (gain / tau2) * (e1 - e2) * inv_diff
    bd0 = 1.0 - e1
    bd1 = gain * (1.0 - e1) - (tau2 / tau1) * ad10
    Ad = np.array([[e1, 0.0], [ad10, e2]], dtype=np.float64)
    Bd = np.array([[bd0], [bd1]], dtype=np.float64)
    Cd = np.array([[0.0, 1.0]], dtype=np.float64)
    return Ad, Bd, Cd


def generate_synthetic_beta(
    n_steps: int,
    ar_coeffs: Tuple[float, ...] = _AR_COEFFS,
    ar_bias: float = _AR_BIAS,
    noise_std: float = _AR_NOISE_STD,
    warmup: int = 500,
    seed: Optional[int] = None,
) -> np.ndarray:
    """Generate a synthetic log-space beta trajectory via an AR process.

    The model is the autonomous (u=0) natural beta process.

    Args:
        n_steps: Number of output time steps.
        ar_coeffs: AR coefficients (a1, a2, ..., ap).
        ar_bias: Constant bias term added each step.
        noise_std: Standard deviation of additive Gaussian noise.
        warmup: Burn-in steps discarded before returning output.
        seed: Random seed for reproducibility.

    Returns:
        beta: Float32 array of shape (n_steps,).
    """
    rng = np.random.default_rng(seed)
    p = len(ar_coeffs)
    total = warmup + n_steps
    hist = np.zeros(p, dtype=np.float64)

    out = np.empty(total, dtype=np.float64)
    for i in range(total):
        ar_term = sum(ar_coeffs[j] * hist[j] for j in range(p))
        noise = rng.standard_normal() * noise_std
        val = ar_term + ar_bias + noise
        out[i] = val
        # Shift history
        hist = np.roll(hist, 1)
        hist[0] = val

    return out[warmup:].astype(np.float32)


def generate_synthetic_stimulation(
    n_steps: int,
    u_max: float = _U_MAX,
    delta_u_max: float = _DELTA_U_MAX,
    switch_interval: int = 1,
    seed: Optional[int] = None,
) -> np.ndarray:
    """Generate a synthetic incremental PRBS stimulation signal.

    Produces a random-walk stimulation that stays within [0, u_max] and
    changes by at most delta_u_max per switch_interval steps.

    Args:
        n_steps: Number of output time steps.
        u_max: Maximum stimulation amplitude.
        delta_u_max: Maximum increment magnitude per switching event.
        switch_interval: Steps between switching events (1 = every step).
        seed: Random seed for reproducibility.

    Returns:
        u: Float32 array of shape (n_steps,), values in [0, u_max].
    """
    rng = np.random.default_rng(seed)
    u = np.empty(n_steps, dtype=np.float32)
    current = u_max / 2.0
    delta = delta_u_max if rng.random() > 0.5 else -delta_u_max

    for i in range(n_steps):
        if i > 0 and i % switch_interval == 0:
            delta = delta_u_max if rng.random() > 0.5 else -delta_u_max
            current = float(np.clip(current + delta, 0.0, u_max))
        u[i] = current

    return u


def generate_modulated_beta(
    n_steps: int,
    seed: Optional[int] = None,
    dt: float = _DT,
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate synthetic beta with PRBS stimulation applied.

    Returns both the observed (modulated) beta signal and the stimulation
    used to produce it.

    Args:
        n_steps: Number of output time steps.
        seed: Random seed for reproducibility.
        dt: Sample period in seconds.

    Returns:
        Tuple of (y_observed, u_stim), each float32 array of shape (n_steps,).
    """
    seed_beta = seed
    seed_stim = None if seed is None else seed + 1
    y_beta = generate_synthetic_beta(n_steps, seed=seed_beta)
    u_stim = generate_synthetic_stimulation(n_steps, seed=seed_stim)

    Ad, Bd, Cd = _build_stim_matrices(dt=dt)
    x = np.zeros(2, dtype=np.float64)
    eta = np.empty(n_steps, dtype=np.float64)

    for i in range(n_steps):
        eta[i] = float((Cd @ x)[0])
        x = Ad @ x + Bd.flatten() * float(u_stim[i])

    y_obs = (y_beta - eta.astype(np.float32)).astype(np.float32)
    return y_obs, u_stim


def generate_demo_patient(
    n_state_y: int = 15,
    n_state_u: int = 15,
    seed: Optional[int] = 42,
    stim_gain: float = _STIM_GAIN,
) -> "PatientData":  # noqa: F821  (forward ref to avoid circular import)
    """Generate a PatientData object populated with synthetic history.

    Suitable for initialising SimulationRunner in tests and demos.

    Args:
        n_state_y: Length of output history buffer.
        n_state_u: Length of input history buffer.
        seed: Random seed for reproducibility.
        stim_gain: Stimulation gain parameter.

    Returns:
        PatientData with synthetic y_history and u_history.
    """
    from dbs_bench.simulation.simulate import PatientData

    warmup_beta = generate_synthetic_beta(
        n_steps=n_state_y + 100,
        seed=seed,
    )
    y_history = warmup_beta[:n_state_y]

    rng = np.random.default_rng(seed)
    u_history = (rng.random(n_state_u) * _U_MAX * 0.5).astype(np.float32)

    return PatientData(
        y_history=y_history,
        u_history=u_history,
        stim_gain=stim_gain,
        stim_tau1=_STIM_TAU1,
        stim_tau2=_STIM_TAU2,
    )


def generate_demo_dataset(
    duration: float = 60.0,
    dt: float = _DT,
    seed: Optional[int] = 42,
    n_state_y: int = 15,
) -> Tuple[np.ndarray, "PatientData"]:  # noqa: F821
    """Generate a synthetic dataset for demos and integration tests.

    Args:
        duration: Duration in seconds.
        dt: Sample period in seconds.
        seed: Random seed.
        n_state_y: History buffer length for the patient object.

    Returns:
        Tuple of (beta_trajectory, PatientData).
        ``beta_trajectory`` is the full observed beta signal (float32,
        shape ``(n_steps,)``); PatientData is initialised from the first
        ``n_state_y`` samples.
    """
    n_steps = int(round(duration / dt))
    beta, _ = generate_modulated_beta(n_steps, seed=seed, dt=dt)
    patient = generate_demo_patient(n_state_y=n_state_y, seed=seed)
    return beta, patient
